# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

localVolumes:
  inputDataPath: /local-volumes/input-data/
  populationsPath: /local-volumes/populations/
  scenariosPath: /local-volumes/scenarios/

dockerContainers:
  dataPreparationActivityModel: kornelro/abm-0-data-preparation-activity-model
  dataPreparationFacilities: kornelro/abm-0-data-preparation-facilities
  dataPreparationNetwork: kornelro/abm-0-data-preparation-network
  dataPreparationTrafficCounts: kornelro/abm-0-data-preparation-traffic-counts
  simulationActivityModel: kornelro/abm-1-simulation-activity-model
  simulationPopulation: kornelro/abm-1-simulation-population
  simulationTrafficModel: kornelro/abm-1-simulation-traffic-model
  postProcessing: kornelro/abm-2-post-processing

dataPreparation: true

simulation:
  populationSize: '1000'
  simulatorsInstances: 2
  simulationsNumberPerInstance: 2

postProcessing:
  hexSize: '9'