{{- if .Values.dataPreparation }}
apiVersion: batch/v1
kind: Job
metadata:
  name: 0-data-preparation-facilities
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      containers:
        - name: 0-data-preparation-facilities
          image: {{ .Values.dockerContainers.dataPreparationFacilities }}
          command: ["./run.sh", "data"]
          volumeMounts:
          - mountPath: /home/workdir/data
            name: input-data-pv
      volumes:
      - name: input-data-pv
        persistentVolumeClaim:
          claimName: input-data-pvc
      restartPolicy: Never
  backoffLimit: 4
{{- end }}