apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: input-data-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 16Gi
  volumeName: input-data-pv