{{- $mypvc := (lookup "v1" "PersistentVolume" .Release.Namespace (printf "input-data-pv")) }}
{{- if not $mypvc }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: input-data-pv
  labels:
    name: input-data-pv
    type: local
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
spec:
  storageClassName: manual
  capacity:
    storage: 32Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.localVolumes.inputDataPath }}
{{- end -}}