{{- $mypvc := (lookup "v1" "PersistentVolumeClaim" .Release.Namespace (printf "input-data-pvc")) }}
{{- if not $mypvc }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: input-data-pvc
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 32Gi
  volumeName: input-data-pv
{{- end -}}