apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: populations-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 16Gi
  volumeName: populations-pv