apiVersion: v1
kind: PersistentVolume
metadata:
  name: scenarios-pv
  labels:
    name: scenarios-pv
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 32Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.localVolumes.scenariosPath }}