apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scenarios-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 32Gi
  volumeName: scenarios-pv